In [1]:
#pip install pandas numpy scikit-learn matplotlib

In [2]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r"C:\Users\prath\Desktop\Phishing Detection\dataset\phishing_and_benign_websites.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\prath\\OneDrive\\Desktop\\Phishing Detection\\dataset\\phishing_and_benign_websites.csv'

In [ ]:
df.columns

Index(['URLs', 'Label'], dtype='object')

In [ ]:
# Check missing values
print("Missing values:")
print(df.isnull().sum())

Missing values:
URLs     0
Label    0
dtype: int64

In [ ]:
# Check duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 2435

In [ ]:
# Remove duplicates if any
df = df.drop_duplicates()

In [ ]:
# Check duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
# Check label distribution
print("Label counts:")
print(df['Label'].value_counts())

Label counts:
Label
Benign      18701
Phishing    17664
Name: count, dtype: int64

In [ ]:
# Dataset info
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 36365 entries, 0 to 38799
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   URLs    36365 non-null  object
 1   Label   36365 non-null  object
dtypes: object(2)
memory usage: 852.3+ KB
None

In [ ]:
def url_length(url):
    return len(url)

df['url_length'] = df['URLs'].apply(url_length)

df.head()

                                          URLs   Label  url_length
0                     http://www.wmmayhem.com/  Benign          24
1  http://www.ballymenaunitedyouthacademy.com/  Benign          43
2              http://www.brusselsgaybars.com/  Benign          31
3          http://www.sportsbettingtennis.net/  Benign          35
4                         http://www.i29.mobi/  Benign          20

In [ ]:
def dot_count(url):
    return url.count('.')

df['dot_count'] = df['URLs'].apply(dot_count)

df.head()

                                          URLs   Label  url_length  dot_count
0                     http://www.wmmayhem.com/  Benign          24          2
1  http://www.ballymenaunitedyouthacademy.com/  Benign          43          2
2              http://www.brusselsgaybars.com/  Benign          31          2
3          http://www.sportsbettingtennis.net/  Benign          35          2
4                         http://www.i29.mobi/  Benign          20          2

In [ ]:
def hyphen_count(url):
    return url.count('-')

df['hyphen_count'] = df['URLs'].apply(hyphen_count)

df.head()

,URLs,Label,url_length,dot_count,hyphen_count
0,http://www.wmmayhem.com/,Benign,24,2,0
1,http://www.ballymenaunitedyouthacademy.com/,Benign,43,2,0
2,http://www.brusselsgaybars.com/,Benign,31,2,0
3,http://www.sportsbettingtennis.net/,Benign,35,2,0
4,http://www.i29.mobi/,Benign,20,2,0

In [ ]:
def slash_count(url):
    return url.count('/')

df['slash_count'] = df['URLs'].apply(slash_count)

In [ ]:
def digit_count(url):
    count = 0
    for i in url:
        if i.isdigit():
            count += 1
    return count

df['digit_count'] = df['URLs'].apply(digit_count)

In [ ]:
def at_count(url):
    return url.count('@')

df['at_count'] = df['URLs'].apply(at_count)

In [ ]:
def question_count(url):
    return url.count('?')

df['question_count'] = df['URLs'].apply(question_count)

In [ ]:
def equal_count(url):
    return url.count('=')

df['equal_count'] = df['URLs'].apply(equal_count)

In [ ]:
def percent_count(url):
    return url.count('%')

df['percent_count'] = df['URLs'].apply(percent_count)

In [ ]:
def subdomain_count(url):
    return url.count('.') - 1

df['subdomain_count'] = df['URLs'].apply(subdomain_count)

In [ ]:
import re

def has_ip(url):
    ip_pattern = r'(\d{1,3}\.){3}\d{1,3}'
    
    if re.search(ip_pattern, url):
        return 1
    else:
        return 0

df['has_ip'] = df['URLs'].apply(has_ip)

In [ ]:
def suspicious_words(url):
    
    words = ['login', 'verify', 'update', 'bank', 'free', 'secure']
    
    for word in words:
        if word in url.lower():
            return 1
            
    return 0

df['suspicious_words'] = df['URLs'].apply(suspicious_words)

In [ ]:
def special_char_count(url):

    special_chars = ['~', '!', '$', '*', '(', ')', ',', ';']

    count = 0

    for char in special_chars:
        count += url.count(char)

    return count

df['special_char_count'] = df['URLs'].apply(special_char_count)

In [ ]:
from urllib.parse import urlparse

def hostname_length(url):

    try:
        return len(urlparse(url).netloc)
    except:
        return 0

df['hostname_length'] = df['URLs'].apply(hostname_length)

In [ ]:
from urllib.parse import urlparse

def path_length(url):

    try:
        return len(urlparse(url).path)
    except:
        return 0

df['path_length'] = df['URLs'].apply(path_length)

In [ ]:
def digit_ratio(url):

    digits = sum(c.isdigit() for c in url)

    return digits / len(url)

df['digit_ratio'] = df['URLs'].apply(digit_ratio)

In [ ]:
def has_shortener(url):

    shorteners = [
        'bit.ly',
        'tinyurl.com',
        'goo.gl',
        't.co',
        'ow.ly'
    ]

    for site in shorteners:
        if site in url.lower():
            return 1

    return 0

df['has_shortener'] = df['URLs'].apply(has_shortener)

In [ ]:
df.head()

,URLs,Label,url_length,dot_count,hyphen_count,slash_count,digit_count,at_count,question_count,equal_count,percent_count,subdomain_count,has_ip,suspicious_words,special_char_count,hostname_length,path_length,digit_ratio,has_shortener
0,http://www.wmmayhem.com/,Benign,24,2,0,3,0,0,0,0,0,1,0,0,0,16,1,0.0,0
1,http://www.ballymenaunitedyouthacademy.com/,Benign,43,2,0,3,0,0,0,0,0,1,0,0,0,35,1,0.0,0
2,http://www.brusselsgaybars.com/,Benign,31,2,0,3,0,0,0,0,0,1,0,0,0,23,1,0.0,0
3,http://www.sportsbettingtennis.net/,Benign,35,2,0,3,0,0,0,0,0,1,0,0,0,27,1,0.0,0
4,http://www.i29.mobi/,Benign,20,2,0,3,2,0,0,0,0,1,0,0,0,12,1,0.1,0

In [ ]:
X = df[
    [
        'url_length',
        'dot_count',
        'hyphen_count',
        'slash_count',
        'digit_count',
        'at_count',
        'question_count',
        'equal_count',
        'percent_count',
        'subdomain_count',
        'has_ip',
        'suspicious_words',
        'special_char_count',
        'hostname_length',
        'path_length',
        'digit_ratio',
        'has_shortener'
    ]
]
y = df['Label']

In [ ]:
df.columns

Index(['URLs', 'Label', 'url_length', 'dot_count', 'hyphen_count',
       'slash_count', 'digit_count', 'at_count', 'question_count',
       'equal_count', 'percent_count', 'subdomain_count', 'has_ip',
       'suspicious_words', 'special_char_count', 'hostname_length',
       'path_length', 'digit_ratio', 'has_shortener'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [ ]:
lr_model = LogisticRegression(max_iter=10000)

lr_model.fit(X_train, y_train)

lr_pred = lr_model.predict(X_test)

lr_acc = accuracy_score(y_test, lr_pred)
lr_prec = precision_score(y_test, lr_pred, pos_label="Phishing")
lr_rec = recall_score(y_test, lr_pred, pos_label="Phishing")
lr_f1 = f1_score(y_test, lr_pred, pos_label="Phishing")

print("Accuracy :", lr_acc)
print("Precision:", lr_prec)
print("Recall   :", lr_rec)
print("F1 Score :", lr_f1)

Accuracy : 0.7156606627251478
Precision: 0.8
Recall   : 0.5572755417956656
F1 Score : 0.656934306569343

In [ ]:
dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

dt_pred = dt_model.predict(X_test)

dt_acc = accuracy_score(y_test, dt_pred)
dt_prec = precision_score(y_test, dt_pred, pos_label="Phishing")
dt_rec = recall_score(y_test, dt_pred, pos_label="Phishing")
dt_f1 = f1_score(y_test, dt_pred, pos_label="Phishing")

print("Accuracy :", dt_acc)
print("Precision:", dt_prec)
print("Recall   :", dt_rec)
print("F1 Score :", dt_f1)

Accuracy : 0.8504056097896329
Precision: 0.8693437219059035
Recall   : 0.816493104418801
F1 Score : 0.842089985486212

In [ ]:
knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train, y_train)

knn_pred = knn_model.predict(X_test)

knn_acc = accuracy_score(y_test, knn_pred)
knn_prec = precision_score(y_test, knn_pred, pos_label="Phishing")
knn_rec = recall_score(y_test, knn_pred, pos_label="Phishing")
knn_f1 = f1_score(y_test, knn_pred, pos_label="Phishing")

print("Accuracy :", knn_acc)
print("Precision:", knn_prec)
print("Recall   :", knn_rec)
print("F1 Score :", knn_f1)

Accuracy : 0.8262065172556029
Precision: 0.8462934947049925
Recall   : 0.7872220658598368
F1 Score : 0.815689705453485

In [ ]:
nb_model = GaussianNB()

nb_model.fit(X_train, y_train)

nb_pred = nb_model.predict(X_test)

nb_acc = accuracy_score(y_test, nb_pred)
nb_prec = precision_score(y_test, nb_pred, pos_label="Phishing")
nb_rec = recall_score(y_test, nb_pred, pos_label="Phishing")
nb_f1 = f1_score(y_test, nb_pred, pos_label="Phishing")

print("Accuracy :", nb_acc)
print("Precision:", nb_prec)
print("Recall   :", nb_rec)
print("F1 Score :", nb_f1)

Accuracy : 0.690774095971401
Precision: 0.8610188261351052
Recall   : 0.43765831691528284
F1 Score : 0.5803321515208061

In [ ]:
rf_model = RandomForestClassifier(random_state=42)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

rf_acc = accuracy_score(y_test, rf_pred)
rf_prec = precision_score(y_test, rf_pred, pos_label="Phishing")
rf_rec = recall_score(y_test, rf_pred, pos_label="Phishing")
rf_f1 = f1_score(y_test, rf_pred, pos_label="Phishing")

print("Accuracy :", rf_acc)
print("Precision:", rf_prec)
print("Recall   :", rf_rec)
print("F1 Score :", rf_f1)

Accuracy : 0.8773545992025299
Precision: 0.8994296007205044
Recall   : 0.8432310723332395
F1 Score : 0.8704241719930274

In [ ]:
models = {
    "Logistic Regression": lr_model,
    "Decision Tree": dt_model,
    "KNN": knn_model,
    "Naive Bayes": nb_model,
    "Random Forest": rf_model
}

accuracies = {
    "Logistic Regression": lr_acc,
    "Decision Tree": dt_acc,
    "KNN": knn_acc,
    "Naive Bayes": nb_acc,
    "Random Forest": rf_acc
}

best_algorithm = max(accuracies, key=accuracies.get)

best_model = models[best_algorithm]

print("Best Model:", best_algorithm)

Best Model: Random Forest

In [ ]:
best_pred = best_model.predict(X_test)

In [ ]:
print("Final Model Evaluation:")
print("Accuracy :", accuracy_score(y_test, best_pred))
print("Precision:", precision_score(y_test, best_pred, pos_label="Phishing"))
print("Recall   :", recall_score(y_test, best_pred, pos_label="Phishing"))
print("F1 Score :", f1_score(y_test, best_pred, pos_label="Phishing"))

Final Model Evaluation:
Accuracy : 0.8773545992025299
Precision: 0.8994296007205044
Recall   : 0.8432310723332395
F1 Score : 0.8704241719930274

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, best_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[3385  335]
 [ 557 2996]]

In [ ]:
import pickle

with open("../backend/model.pkl", "wb") as f:
    pickle.dump(best_model, f)

print("Model saved successfully!")

Model saved successfully!

In [ ]:
print("Total rows:", len(df))
print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))

Total rows: 36365
Training rows: 29092
Testing rows: 7273